### ISSUE TITLE
Gnome launcher not launching Skype

### ISSUE THREAD

**Issue by Doc73** [flathub/com.skype.Client#107]
Dear Mantainers,
After latest update to v. 8.59.0.77, the launcher does nothing and Skype doesn't start. On the contrary, `flatpak run com.skype.Client` by terminal works fine.

I'm sorry, but I'm not so familiar with Flatpaks and therefore I don't know how to debug this issue.

My System:
Debian 10 Buster 64bit
Gnome 3.30.2

Best regards,
Domenico

**Comment by FakeShemp** [comment]
Should be solved by 6ab8867226eb018245c44569fa5c51013cc6a925

**Comment by Doc73** [comment]
Yes, solved! Thanks!

**Comment by Maltimore** [comment]
Works fine over here as well now. Let's close the issue then!
