### ISSUE TITLE
This is not the skype logo

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/com.skype.Client#120]
Since 2019, Skype has been using the logo shown [here](https://en.wikipedia.org/wiki/Skype#/media/File:Skype_logo_(2019%E2%80%93present).svg)

**Comment by WhyNotHugo** [comment]
> This is not the skype logo #

What do you mean by "this"? If you mean the icon Skype shows, that's included with their application package.

**Comment by lionirdeadman** [comment]
The one shown in the Flathub Frontend (or any frontend using AppStream).

It does not use the one included in the Skype package that we repackage.

Looking at the [AppData.xml](https://github.com/flathub/com.skype.Client/blob/master/com.skype.Client.appdata.xml#L25), it links to an old and pixelated mess taken from the Google Play store. Anyhow, this is not the current logo and has not been for 2years now.

It's possible to get the icon shown on the Google Play store again since it has updated the icon although I'm not sure how to grab the appropriate sized icons.

**Comment by FakeShemp** [comment]
Solved with #171
