### ISSUE TITLE
Screensaver comes on when in full-screen

### ISSUE THREAD

**Issue by physkets** [flathub/com.skype.Client#126]
I'm on a wayland session of KDE Plasma, and the scree saver comes on when I'm using Skype in full-screen mode. Does the flatpak maybe need the `org.freedesktop.ScreenSaver=talk` permission as a `Session Bus Policy`?

**Comment by lunaryorn** [comment]
I've also seen this in Gnome Wayland sessions: During active calls screen darkens and locks eventually, even in non-fullscreen sessions.  `org.freedesktop.ScreenSaver=talk` fixes it.
