### ISSUE TITLE
Cannot screen share on Wayland

### ISSUE THREAD

**Issue by vchernin** [flathub/com.skype.Client#142]
Skype currently cannot screen share on Wayland in the Deb or in the Flatpak.

This is as Skype does not show the share screen button on Wayland, despite Electron supporting Wayland screen sharing. 

Skype not showing the screen share button on Wayland is entirely arbitrary, given one can succesfully screen share from the Skype web app in Chromium (ignoring minor Chromium WebRTC PipeWire bugs).

So if Skype were to remove this restriction, and ship with a semi recent version of Electron, screen sharing would likely work on wayland. Working Electron screen sharing apps include [Jitsi Meet](https://github.com/jitsi/jitsi-meet-electron/issues/567#issuecomment-839917891) and [Slack](https://github.com/flathub/com.slack.Slack/issues/101#issuecomment-808430530) (note we can use the runtime's pipewire 0.3 starting from electron 13).

When Skype enables the share screen button on Wayland a change to the manifest will be needed. We should build in PipeWire support similar to what was done for [Slack Flatpak](https://github.com/flathub/com.slack.Slack/pull/118). 

The combination of Skype making the button visible, the Flatpak building with PipeWire, and passing `--enable-features=WebRTCPipeWireCapturer` should make screen sharing work for Skype on Wayland. Note the need to pass the command line option should be resolved in Chromium eventually.

**Comment by chrisjimallen** [comment]
Happy anniversary Skype issue

**Comment by snaggen** [comment]
This is coming in skype, and is available in the preview according to https://answers.microsoft.com/en-us/skype/forum/all/linux-users-enable-new-calling-experience/fa12eb5b-1702-4b95-8e68-68d97ad184e4

I have not had time to actually test this, but it sounds promising.

**Comment by APanteleychuk** [comment]
They have removed Beta options in the new Skype version ((( The problem with Wayland is actual.

**Comment by Fiamat** [comment]
That's right. The issue remains unresolved. This is ridiculous. 2nd anniversary due to stupid unnecessary `if` in Skype...

**Comment by GermanZun** [comment]
waiting for this too

**Comment by sandikata** [comment]
What a fa****s are Micro****... Well, at all i do not share screens on skype or even using skype in general, but at workplace we are using skype as communication solution..

**Comment by jaymin7359** [comment]
Temporary solution as below.

1.run in terminal echo $XDG_SESSION_TYPE **Output will be** x11 or something
2.sudo nano /etc/gdm3/custom.conf and then uncomment **WaylandEnable=false** and then save
3.Power off and restart the system

**Comment by PatiHox** [comment]
> Temporary solution as below.
> 
> 1.run in terminal - echo $XDG_SESSION_TYPE - **Output will be** x11 or something 2.sudo nano /etc/gdm3/custom.conf and then uncomment **WaylandEnable=false** and then save 3.Power off and restart the system

This solution actually disables the wayland and switches the system to x11. It does technically work, yet you sacrifice wayland altogether.
So be wary!

**Comment by jacek-lewandowski** [comment]
I wonder if it could be achieved with an OBS Studio virtual camera...

**Comment by theblackhole** [comment]
> I wonder if it could be achieved with an OBS Studio virtual camera...

It does, I did use it before finding this opened issue. But it's 720p max, 1080p won't work. So that could be a valid workaround.

Another workaround is to use Skype Web atm because screen sharing works fine with it (Well, in my case it works either by sharing all the screens, or a single window/tab but not a single screen. But that's ok, better than nothing).

**Comment by mtariqsajid** [comment]
i am not able to screen share in   skype 
ubuntu 22.04.3 LTS
skype: 8.107.0.215 snap

**Comment by vasimak** [comment]
When this issue will be resolved. It is over 2 years now and wayland is coming as default in kde 6 and many distros will not support anymore xorg

**Comment by TomaszGasior** [comment]
@mtariqsajid This is not correct place to post Snap related issue. The repository here is where Flatpak (not Snap) package for Skype is maintained.

@vasimak Did you try KDE's Xwayland video bridge software?

**Comment by vasimak** [comment]
> @mtariqsajid This is not correct place to post Snap related issue. The repository here is where Flatpak (not Snap) package for Skype is maintained.
> 
> @vasimak Did you try KDE's Xwayland video bridge software?

No i couldnt. I install it but i couldnt make it to work

**Comment by ablonewolf** [comment]
On KDE 6 in Wayland, screen sharing for Skype hasn't arrived yet. On Fedora 40, the XOrg will be ditched completely in favor of KDE 6. I wonder when this issue will be resolved.

**Comment by vasimak** [comment]
I just removed skype app and i am using chrome based browser(in firefox screen share doesnt work for some reason)  so i can screen share in wayland.  Its not the greatest solution but it works

**Comment by tobehn** [comment]
> I just removed skype app and i am using chrome based browser(in firefox screen share doesnt work for some reason) so i can screen share in wayland. Its not the greatest solution but it works

This is definitely not a solution.

In the very top of this issue it is suggested to

> The combination of Skype making the button visible, the Flatpak building with PipeWire, and passing --enable-features=WebRTCPipeWireCapturer should make screen sharing work for Skype on Wayland. 

Who could do this and who is the person in charge at Skype to probably help with it?

**Comment by nicahokie** [comment]
> I just removed skype app and i am using chrome based browser(in firefox screen share doesnt work for some reason) so i can screen share in wayland. Its not the greatest solution but it works

Furthermore you can also have the browser save it as a shortcut (Similar to PWA but for non-PWA sites) to make it feel more like an App.

**Comment by jivanpal** [comment]
> I had this same problem and solved it by just graphically choosing the **X11** at the S.O. **login screen**.

@gabrielroot As mentioned by other commenters, this is merely a workaround to share screen, not actually a solution to the problem of it not working under Wayland. Many users need/want to use Wayland rather than X11 for numerous reasons.

**Comment by pkejval** [comment]
Add screen sharing on wayland, please! It used to work in preview version one or two years before.

**Comment by romanovzky** [comment]
How has this not been fixed yet?

**Comment by snaggen** [comment]
> How has this not been fixed yet?

Isn't the root cause of this, that Microsoft decided to remove the Pipewire based screensharing they once had in their beta. So that there is basically no way to do screensharing with the Skype App under wayland. As someone points out, if you use the browser version things works. 

So, I don't understand why this bug is open here, for the flatpak?  Shouldn't this be directed to Microsoft? Or does it work for any other packaging version?

**Comment by mtariqsajid** [comment]
I hope flatpak team might add this feature, its anoying when I have to meet in skype I have to use the browser

**Comment by pkejval** [comment]
Well, me and others were in impression that this Flatpak is official distribution by MS. If it isn't, this issue should be closed many years ago...

**Comment by vchernin** [comment]
> Well, me and others were in impression that this Flatpak is official distribution by MS. If it isn't, this issue should be closed many years ago...

Indeed, this needs to be fixed upstream.
