### ISSUE TITLE
Higher quality Flathub image

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.skype.Client#190]
It has occurred to me that the Flathub image is only 64x which is not great. It makes the entire application look quite blurry:

https://flathub.org/apps/details/com.amazon.Workspaces

The same happened with another Flathub application, so check there for additional details:

https://github.com/flathub/com.amazon.Workspaces/issues/25

**Comment by flipflop97** [comment]
Quality should be fixed with #189 after a rebuild. However, it's still using the old icon, which should be updated too.

**Comment by bbhtt** [comment]
The frontend doesn't use >128px, so it should be fixed with https://github.com/flathub/com.skype.Client/pull/199
