### ISSUE TITLE
Skype quits upon window closing

### ISSUE THREAD

**Issue by alexeymuranov** [flathub/com.skype.Client#232]
When I close the Skype window, Skype quits, while the "Upon closing, keep Skype running" option is On.

Skype version: 8.124.0.204.

This is on a freshly installed Linux Mint 22.

**Comment by michalkvasnicka** [comment]
This is the one reason, from many others, why is flag "unverified" good sign to uninstall this flatpak app :)

**Comment by faveoled** [comment]
Doesn't reproduce with 8.125.0.201 on Ubuntu 22.04.4

**Comment by alexeymuranov** [comment]
Indeed, seems to work now.

**Comment by michalkvasnicka** [comment]
But still "unverified" flag, which is really annoying (Linux Mint 22 block automatic "unverified" flatpak apps update!!!)
