### ISSUE TITLE
Can't download files

### ISSUE THREAD

**Issue by diegoviola** [flathub/com.skype.Client#26]
When running Skype with `flatpak run com.skype.Client` I'm unable to download files from Skype, i.e. when I click on a file that has been sent to me it will stay stuck in "Downloading..." (the file is never written to disk because flatpak treats the directory as read only).

If I start flatpak with `flatpak run --filesystem=home:rw com.skype.Client` it works and the file is saved to /home/diego but I'd prefer if the file is saved to ~/Downloads and I don't have to give Skype full read/write permissions.

Thanks.

**Comment by zarelit** [comment]
@balcsida (I mentioned you because it happened that you worked on the package lately): is there any news on this?
As a user I tried to read the docs but couldn't find anything, is there a command to inspect what paths are mounted read-only and whatnot?

**Comment by balcsida** [comment]
Hi @zarelit,

Sorry, but I have no idea. :slightly_frowning_face:

**Comment by zarelit** [comment]
@diegoviola At present this package treats the home read-only and gives write access to the download directory. I think your issue is that you don't have the ~/Downloads directory set as an XDG user dir. Are you using Arch maybe?
If that's the case install `xdg-user-dirs` and then tell the system which directory you consider Download by using `xdg-user-dirs-update --set DOWNLOAD ~/Downloads`

**Comment by diegoviola** [comment]
I'm not longer affected by this issue, mostly because I stopped using Skype altogether and no longer have an account to test it.

@zarelit Yes, I was/am using Arch and didn't have `xdg-user-dirs` installed IIRC.

I will close the issue and assume it's fixed as per your comment, feel free to re-open if it isn't.

Sorry for taking so long to respond to this and thanks for your feedback.

**Comment by diegoviola** [comment]
Oh, hrm... considering that #30 is open, I'm not sure I should have closed this.

@zarelit any pointers?

Thanks.
