### ISSUE TITLE
Skype shortcut is not being installed

### ISSUE THREAD

**Issue by marcosps** [flathub/com.skype.Client#3]
Thus, Cinnamon menu is not able to list Skype app from the UI.

**Comment by TingPing** [comment]
Is this your first flatpak? You may need to logout for Cinnamon to pick it up.

**Comment by marcosps** [comment]
Not as all, I'm using Spotify flatpak app for some months, and even after restarting the Cinnamon (after reinstalling the flatpak app), it didn't worked.

**Comment by snaggen** [comment]
Looking on my system I see the file 
/var/lib/flatpak/exports/share/applications/com.skype.Client.desktop
so it seems that the desktop file is exported. Do you see this file (or a file in .local/share/flatpak/exports/share/applications)? 

Is XDG_DATA_DIRS  set correctly?

**Comment by marcosps** [comment]
@snaggen Slack worked here, so I think that problem lies in my flatpak prefix installation, which was wrong here. Sorry, my mistake.
