### ISSUE TITLE
Auto startup on boot is not performed

### ISSUE THREAD

**Issue by rconway** [flathub/com.skype.Client#36]
[kubuntu 18.04]

Despite the in-app setting to auto startup on boot, this does not occur. The app has to be launched manually.

May relate to issue #20 (gnome-keyring dependency) - as after launching manually I am prompted to unlock the gnome keyring.

**Comment by barthalion** [comment]
It's by design. Applications managing autostart on their own pretty much defeats any measures Flatpak does by sandboxing.

**Comment by TingPing** [comment]
See also: https://github.com/flatpak/flatpak/issues/118
