### ISSUE TITLE
skype run failed

### ISSUE THREAD

**Issue by jacknlliu** [flathub/com.skype.Client#4]
```sh
$ flatpak run com.skype.Client
Can't find source path /tmp/.X11-unix/X1: No such file or directory
```

**Comment by TingPing** [comment]
Do other X11 applications run under Flatpak?

**Comment by jacknlliu** [comment]
It seems that other flatpak package also did not work.

**Comment by TingPing** [comment]
This issue has been reported at flatpak/flatpak#938 since it affects multiple applications.
