### ISSUE TITLE
Broken tray icon

### ISSUE THREAD

**Issue by bertogg** [flathub/com.skype.Client#44]
The Skype tray icon that appears on the lower left side of my GNOME desktop is broken. I haven't debugged it but it looks like it's the wrong size.

Here's a screenshot, next to the Linphone icon for comparison:

https://people.debian.org/~berto/files/skype.png

**Comment by RoyiAvital** [comment]
It happens on Linux Mint 18.3 as well.

**Comment by RoyiAvital** [comment]
Could we update this to the newest Skype version?

**Comment by TingPing** [comment]
@RoyiAvital 	Updated, let me know if all is good.

**Comment by bertogg** [comment]
Still broken for me (using 8.34.0.78).

**Comment by bertogg** [comment]
**edit:** working fine now. Maybe I just needed to restart the session? Sorry for the noise.
