### ISSUE TITLE
Cannot install (error: Wrong size for extra data https://repo.skype.com/latest/skypeforlinux-64.deb)

### ISSUE THREAD

**Issue by dsboger** [flathub/com.skype.Client#6]
When I try to install using the command from flathub site, I get the following:

```
$ LANG=C flatpak install --from https://flathub.org/repo/appstream/com.skype.Client.flatpakref
Installing: com.skype.Client/x86_64/stable
Installing: com.skype.Client/x86_64/stable from flathub
[####################] Downloading: 67,0 MB/66,7 MB (1,7 MB/s)                 
error: Wrong size for extra data https://repo.skype.com/latest/skypeforlinux-64.deb
```

Thanks for your efforts!

**Comment by zkanda** [comment]
I'm getting this error too. :)

**Comment by neingeist** [comment]
Same here.

**Comment by neingeist** [comment]
The JSON points to https://repo.skype.com/latest/skypeforlinux-64.deb, I suggest using one of these URLs/packages here:

https://repo.skype.com/deb/pool/main/s/skypeforlinux/

**Comment by poroiliev** [comment]
Still getting error message:
Wrong size for extra data https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.11.76.8_amd64.deb
