### ISSUE TITLE
Bump to v8.47.76.58

### ISSUE THREAD

**Issue by AquaL1te** [flathub/com.skype.Client#60]
New version is released. See for full overview: https://repo.skype.com/deb/pool/main/s/skypeforlinux/

**Comment by develop7** [comment]
interesting, https://support.skype.com/en/faq/FA34778/release-notes-for-skype-for-windows-mac-linux-and-web doesn't metion it

**Comment by vasyugan** [comment]
@de

For weeks now I got a persistent notification in Skype which tells me to quit and update it. The faq says:

"Skype for Linux 8.47.0.73  begins rolling out June 13, 2019, and releases gradually over the next week."

So this does not look like a pre-release. Flathub currently has 8.45.0.41

**Comment by vasyugan** [comment]
@develop7 when you download it manually, you get version  8.47.0.59, so flathub is still several minor versions behind.

**Comment by develop7** [comment]
> The faq says:
> 
> "Skype for Linux 8.47.0.73 begins rolling out June 13, 2019, and releases gradually over the next week."

Ya, well, *now* it does, it didn't on Jun 10.

**Comment by guilindner** [comment]
We are at version 8.48.0.51 now (rolling out June 26, 2019)

**Comment by xshram** [comment]
> We are at version 8.48.0.51 now (rolling out June 26, 2019)

How did you install it? I installed com.skype.Client today and it's 8.45.041

**Comment by guilindner** [comment]
> > We are at version 8.48.0.51 now (rolling out June 26, 2019)
> 
> How did you install it? I installed com.skype.Client today and it's 8.45.041

Sorry, I mean Skype is at version 8.48. The flatpak package is getting far behind.

**Comment by develop7** [comment]
#61

**Comment by ramcq** [comment]
Fixed by #74 and #77
