### ISSUE TITLE
Please update to 8.54.0.91

### ISSUE THREAD

**Issue by Tedd-the-Tiger** [flathub/com.skype.Client#83]
Latest stable version as of this posting is 8.54.0.91 and was released on November 4, 2019.
[https://support.skype.com/en/faq/FA34778/what-s-new-in-skype-for-windows-mac-linux-and-web](https://support.skype.com/en/faq/FA34778/what-s-new-in-skype-for-windows-mac-linux-and-web
)

**Comment by muelli** [comment]
this is done now, no?

**Comment by Tedd-the-Tiger** [comment]
At the exact time I opened this issue, the flatpak update process didn't
see version 8.54.0.91 and neither did flathub. I see now it has. Thanks.
This can now be closed.
