### ISSUE TITLE
No connection since 2020-01-24

### ISSUE THREAD

**Issue by flaphoschi** [flathub/com.skype.Client#89]
Hello!

My Skype lost the connection on last friday, like often without actual signaling about it and kept my status on available. After I recognized that I don't receive any messages I restarted it, now it keeps saying I have no internet connection.

I reinstalled the application and also removed all files from my home directory, which remained. Nothing helped. So I switched the regular skype-preview-package from Archlinux, it works fine.

**Comment by phw** [comment]
Same for me. I can't tell the exact date, but since an upgrade a few days ago this happens. Skype does start and appears to run, but it does neither receive nor send messages.

I tried downgrading com.skype.Client to commits 47cc4061a9ff7fb5e397d719e402e3f8c3d293ca061e5401c43add7cc14174e8 and 9dae03c0e670598c25341e3eb97e92c98547172ffb1c47ba506568bad1b7ae54 but that doesn't change anything. So I suspect it was a runtime update that broke things.

**Comment by flaphoschi** [comment]
I'm not sure if I did a update of the runtime. Where is the logfile of flatpak? I don't find and documentation about it.

**Comment by phw** [comment]
Spotify broke in a similar way: https://github.com/flathub/com.spotify.Client/issues/116

I wonder if this is related. So far I could not figure out what is happening:

- I tried downgrading Flatpak to 1.5.2 (before was 1.6.0)
- I tried downgrading the org.freedesktop.Platform to the version from 2019-12-09 (and then  even one version before that) with:

      sudo flatpak update --commit 7b0f3ed6f069a1ac57a6a26fb659f2c0c24b2e31fe47617753086db3605ddc55 org.freedesktop.Platform//19.08
- As I wrote above I also downgraded com.skype.Client.

Behavior is always the same. Also using Arch Linux. The Skype app does not output anything when I run it from terminal with flatpak run com.skype.Client. Not sure how to get more debug details.

> I'm not sure if I did a update of the runtime. Where is the logfile of flatpak?

I don't know whether this is logged, but if you run flatpak update it would update them by default. You can ask for the available version for a runtime with:

    flatpak remote-info --log flathub org.freedesktop.Platform//19.08

Then one can try installing a specific commit with the command I posted above.

**Comment by phw** [comment]
> Spotify broke in a similar way: [flathub/com.spotify.Client#116](https://github.com/flathub/com.spotify.Client/issues/116)

Steam has similar issues reporting network connection errors. So I guess it is really not a problem with the Skype package but rather something else broke networking for flatpak app (partially?) for @flaphoschi  and myself.

**Comment by smcv** [comment]
See also p11-glue/p11-kit#275, flatpak/flatpak#3388.

**Comment by flaphoschi** [comment]
Fix by a revert for [p11-kit](https://github.com/p11-glue/p11-kit/issues/275).
